name = "commonsense-solar-monitor"
main = "src/index.js"
compatibility_date = "2026-10-01"
workers_dev = true

[triggers]
crons = ["0 * * * *"]

[vars]
ALLOWED_ORIGIN = "https://geeking.commonsense.com.au"
BATTERY_CAPACITY_KWH = "41.93"
AMBER_SITE_ID = ""

[[d1_databases]]
binding = "DB"
database_name = "commonsense-solar-readings"
database_id = "95d6dbef-3503-4b40-a220-e8b992c82f83"
